version: '3.0'
services:
  web:
    build: .
    ports:
      - "9090:9090"
    volumes:
      - ".:/app:rw"
    networks:
      - backend

  kafka:
    build: ./kafka
    restart: on-failure:3
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      - backend

  zookeeper:
    build: ./zookeeper
    ports:
      - "2181:2181"
    networks:
      - backend

  db:
    image: mysql
    restart: always
    volumes:
      - ../db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend
networks:
  backend:
    driver: bridge
