apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-broker
  name: kafka-broker
spec:
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  - name: "9093"
    port: 9093
    targetPort: 9093
  - name: "9094"
    port: 9094
    targetPort: 9094
  selector:
    io.kompose.service: kafka-broker
status:
  loadBalancer: {}
