apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-broker
  name: kafka-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka-broker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: kafka-broker
    spec:
      containers:
      - env:
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "true"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: 172.17.0.2
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_CREATE_TOPICS
          value: albumNotification:1:1
        - name: KAFKA_DELETE_TOPIC_ENABLE
          value: "true"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: INSIDE
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
        - name: KAFKA_MESSAGE_MAX_BYTES
          value: "200000000"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        image: wurstmeister/kafka
        imagePullPolicy: ""
        name: kafka-broker
        ports:
        - containerPort: 9092
        - containerPort: 9093
        - containerPort: 9094
        resources: {}
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: kafka-broker-claim0
        - mountPath: /tmp/kafka-logs
          name: kafka-broker-claim1
        - mountPath: /tmp/zookeeper
          name: kafka-broker-claim2
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: kafka-broker-claim0
        persistentVolumeClaim:
          claimName: kafka-broker-claim0
      - name: kafka-broker-claim1
        persistentVolumeClaim:
          claimName: kafka-broker-claim1
      - name: kafka-broker-claim2
        persistentVolumeClaim:
          claimName: kafka-broker-claim2
status: {}
