basePath: /
consumes:
- application/json
definitions:
  Response:
    description: Wrapper for all responses form the system
    properties:
      message:
        description: Description on what happened to the request
        type: string
        x-go-name: Message
      model:
        description: Data returned from API as part of request
        type: object
        x-go-name: Model
      status:
        description: Status of the request
        type: string
        x-go-name: Status
    type: object
    x-go-package: photo_album/helpers
host: localhost:9090
info:
  description: RestfulAPI for implementing photo album
  title: Documentation for Photo Album MicroService
  version: 1.0.0
paths:
  /album:
    get:
      description: Returns a list of all albums in the system
      operationId: listAlbums
      responses:
        "200":
          description: Response
          schema:
            $ref: '#/definitions/Response'
      tags:
      - album
    post:
      description: Returns a 200 in case of success
      operationId: saveAlbum
      responses:
        "200":
          description: Response
          schema:
            $ref: '#/definitions/Response'
      tags:
      - album
  /album/{album_id}/image:
    get:
      description: Returns a list of images in the album
      operationId: listAllImagesOfSelectedImages
      responses:
        "200":
          description: Response
          schema:
            $ref: '#/definitions/Response'
      tags:
      - image
    post:
      operationId: addImageToAlbum
      responses:
        "200":
          description: Response
          schema:
            $ref: '#/definitions/Response'
      summary: Returns a 200 in case of success.
      tags:
      - image
  /album/{album_id}/image/{image_id}:
    delete:
      operationId: deleteImageFromAlbum
      responses:
        "200":
          description: Response
          schema:
            $ref: '#/definitions/Response'
      summary: Returns a 200 in case of success.
      tags:
      - image
  /album/{id}:
    delete:
      description: Returns a 200 in case of success
      operationId: deleteAlbum
      responses:
        "200":
          description: Response
          schema:
            $ref: '#/definitions/Response'
      tags:
      - album
produces:
- application/json
responses:
  ResponseWrapper:
    description: Main wrapper for response
    schema:
      $ref: '#/definitions/Response'
schemes:
- http
swagger: "2.0"
