FROM mysql:latest
ENV MYSQL_ROOT_PASSWORD: root@123
ENV MYSQL_DATABASE: photo-album
ENV MYSQL_USER: photo-album
ENV MYSQL_PASSWORD: photo-album
CMD ["--default-authentication-plugin=mysql_native_password"]